In [1]:
using Pkg
Pkg.add("Gurobi")
Pkg.bulid("Gurobi")

    Updating registry at `~/.julia/registries/General`
┌ Error: curl_easy_setopt: 48
└ @ Downloads.Curl /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Downloads/src/Curl/utils.jl:36
┌ Error: curl_easy_setopt: 48
└ @ Downloads.Curl /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Downloads/src/Curl/utils.jl:36
┌ Error: curl_easy_setopt: 48
└ @ Downloads.Curl /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Downloads/src/Curl/utils.jl:36
┌ Error: curl_easy_setopt: 48
└ @ Downloads.Curl /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Downloads/src/Curl/utils.jl:36
┌ Error: curl_easy_setopt: 48
└ @ Downloads.Curl /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Downloads/src/Curl/utils.jl:36
┌ Error: curl_easy_setopt: 48
└ @ Downloads.Curl /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Downloads/src/Curl/uti

LoadError: Error building `Gurobi`: 
ERROR: LoadError: Unable to locate Gurobi installation. If the advice above did not help,
open an issue at https://github.com/jump-dev/Gurobi.jl and post the full
print-out of this diagnostic attempt.

Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] top-level scope
   @ ~/.julia/packages/Gurobi/A9YqC/deps/build.jl:167
 [3] include(fname::String)
   @ Base.MainInclude ./client.jl:444
 [4] top-level scope
   @ none:5
in expression starting at /Users/user5/.julia/packages/Gurobi/A9YqC/deps/build.jl:160

**Unable to locate Gurobi installation. Running some common diagnostics.**

Gurobi.jl only supports the following versions:

 - gurobi95
 - gurobi91
 - gurobi90

Did you download and install one of these versions from gurobi.com?
Installing Gurobi.jl via the Julia package manager is _not_ sufficient!

We couldn't find the `GUROBI_HOME` environment variable, but we
found this version of Gurobi on your `PATH`.

Gurobi Optimizer version 9.0.3 build v9.0.3rc0 (mac64)
Copyright (c) 2020, Gurobi Optimization, LLC

Is this version one of the supported versions listed above? If so,
we found the executable, but not the libraries we need. Follow the
advice below to set the `GUROBI_HOME` environment variable. If not,
you should edit your `PATH` to point to the correct version, or set
the `GUROBI_HOME` environment variable.

You should set the `GUROBI_HOME` environment variable to point to the
install location then try again. For example (updating the path to the
correct location if needed):
```
# On Windows, this might be
ENV["GUROBI_HOME"] = "C:\\Program Files\\gurobi950\\win64\\"
import Pkg
Pkg.add("Gurobi")
Pkg.build("Gurobi")

# On OSX, this might be
ENV["GUROBI_HOME"] = "/Library/gurobi950/mac64/"
import Pkg
Pkg.add("Gurobi")
Pkg.build("Gurobi")

# On Unix, this might be
ENV["GUROBI_HOME"] = "/opt/gurobi950/linux64/"
import Pkg
Pkg.add("Gurobi")
Pkg.build("Gurobi")
```
**Note: your path may differ. Check which folder you installed the Gurobi
binary in, and update the path accordingly.**


In [1]:


using MatrixDepot, IterativeSolvers
md = mdopen("SNAP/web-Google")
mdinfo(md)

A = md.A
outdegree = sum(A, dims=2)
indegree = sum(A, dims=1)

using LinearAlgebra, SparseArrays
n = size(A,1)
outdegree = convert.(Float64, outdegree)
# outdegree[outdegree .== 0] .= (1/n)
# outdegree[outdegree .== 0] .= n

# mat = LinearMap(I - spdiagm(vec(outdegree))*LinearMap(A)*0.8)
# b = LinearMap(0.2/n*ones(n))

# gmres!(ones(n)/n, mat, 0.2/n*ones(n)) # 10시까지 돌려보자!

ii = findall(x->x==0, outdegree)
i1 = getindex.(ii, 1)



using LinearMaps
a = zeros(n)
a[i1,:] .= 1
J = LinearMap(ones(n,1))*LinearMap(ones(1,n))
# A_partial_trans = J*LinearMap(Diagonal(a./n))

# J = kron(LinearMap(Matrix{Float64}(I, 76369, 76369)), LinearMap(Matrix{Float64}(I, 12, 12)))
A_partial = LinearMap(Diagonal(a./n))*J # dangling -> 1/n prob.



# outdegree[outdegree .== 0] .= 1
R_inv = LinearMap(Diagonal((ones(n)./ outdegree)[:,1]))

p=0.8
A = LinearMap(convert.(Float64,md.A))
P = (1-p)/n * J + p * (R_inv*A + A_partial)


using IterativeSolvers

π1 = ones(n)./n
gmres!(π1,I-transpose(P), zeros(n))

include group.jl for user defined matrix generators
verify download of index files...
reading database
adding metadata...
adding svd data...
writing database
used remote sites are sparse.tamu.edu with MAT index and math.nist.gov with HTML index


916428-element Vector{Float64}:
 3.134134298396244e-5
 1.8932277880202163e-6
 3.5653144716835955e-6
 8.158872905969429e-7
 9.106901298254041e-7
 1.819798703278862e-6
 3.024353832181621e-7
 6.715935571759826e-7
 5.705074243274775e-7
 3.326789215579808e-7
 2.922246346304535e-6
 7.264821579064055e-7
 3.024353832181621e-7
 ⋮
 1.2210062473522803e-6
 5.2242957085228576e-6
 2.9316575667581142e-6
 9.436794244633382e-7
 7.219820797408957e-7
 8.164282557823939e-7
 3.024353832181621e-7
 1.6376558963728642e-6
 4.4964682851926755e-7
 3.024353832181621e-7
 8.083326101029732e-6
 7.330951429043519e-7

In [85]:
using LinearMaps
a = zeros(n)
a[i1,:] .= 1
J = LinearMap(ones(n,1))*LinearMap(ones(1,n))
# A_partial_trans = J*LinearMap(Diagonal(a./n))

# J = kron(LinearMap(Matrix{Float64}(I, 76369, 76369)), LinearMap(Matrix{Float64}(I, 12, 12)))
A_partial = LinearMap(Diagonal(a./n))*J # dangling -> 1/n prob.



# outdegree[outdegree .== 0] .= 1
R_inv = LinearMap(Diagonal((ones(n)./ outdegree)[:,1]))

p=0.8
A = LinearMap(convert.(Float64,md.A))
P = (1-p)/n * J + p * (R_inv*A + A_partial)

916428×916428 LinearMaps.LinearCombination{Float64} with 2 maps:
  916428×916428 LinearMaps.ScaledMap{Float64} with scale: 2.1823863958761623e-7 of
    916428×916428 LinearMaps.CompositeMap{Float64} with 2 maps:
      1×916428 LinearMaps.WrappedMap{Float64} of
        1×916428 Matrix{Float64}
      916428×1 LinearMaps.WrappedMap{Float64} of
        916428×1 Matrix{Float64}
  916428×916428 LinearMaps.ScaledMap{Float64} with scale: 0.8 of
    916428×916428 LinearMaps.LinearCombination{Float64} with 2 maps:
      916428×916428 LinearMaps.CompositeMap{Float64} with 2 maps:
        916428×916428 LinearMaps.WrappedMap{Float64} of
          916428×916428 SparseMatrixCSC{Float64, Int64}
        916428×916428 LinearMaps.WrappedMap{Float64} of
          916428×916428 Diagonal{Float64, Vector{Float64}}
      916428×916428 LinearMaps.CompositeMap{Float64} with 3 maps:
        1×916428 LinearMaps.WrappedMap{Float64} of
          1×916428 Matrix{Float64}
        916428×1 LinearMaps.WrappedMap{Float6

In [87]:
using IterativeSolvers

π1 = ones(n)./n
gmres!(π1,I-transpose(P), zeros(n))

916428-element Vector{Float64}:
 3.134134298396244e-5
 1.8932277880202163e-6
 3.5653144716835955e-6
 8.158872905969429e-7
 9.106901298254041e-7
 1.819798703278862e-6
 3.024353832181621e-7
 6.715935571759826e-7
 5.705074243274775e-7
 3.326789215579808e-7
 2.922246346304535e-6
 7.264821579064055e-7
 3.024353832181621e-7
 ⋮
 1.2210062473522803e-6
 5.2242957085228576e-6
 2.9316575667581142e-6
 9.436794244633382e-7
 7.219820797408957e-7
 8.164282557823939e-7
 3.024353832181621e-7
 1.6376558963728642e-6
 4.4964682851926755e-7
 3.024353832181621e-7
 8.083326101029732e-6
 7.330951429043519e-7

In [25]:
LinearMap(ones(n))*LinearMap(transpose(ones(n)))

916428×916428 LinearMaps.CompositeMap{Float64} with 2 maps:
  1×916428 LinearMaps.WrappedMap{Float64} of
    1×916428 transpose(::Vector{Float64}) with eltype Float64
  916428×1 LinearMaps.WrappedMap{Float64} of
    916428-element Vector{Float64}

In [30]:
J

916428×916428 LinearMaps.KroneckerMap{Float64} with 2 maps:
  76369×76369 LinearMaps.WrappedMap{Float64} of
    76369×76369 Matrix{Float64}
  12×12 LinearMaps.WrappedMap{Float64} of
    12×12 Matrix{Float64}

In [3]:
using LinearMaps
a = zeros(n)
a[i1,:] .= 1
# J = LinearMap(ones(n))*LinearMap(ones(n))'
J = kron(LinearMap(Matrix{Float64}(I, 76369, 76369)), LinearMap(Matrix{Float64}(I, 12, 12)))
A_partial = LinearMap(Diagonal(a./n))*J # dangling -> 1/n prob.

916428×916428 LinearMaps.CompositeMap{Float64} with 2 maps:
  916428×916428 LinearMaps.KroneckerMap{Float64} with 2 maps:
    76369×76369 LinearMaps.WrappedMap{Float64} of
      76369×76369 Matrix{Float64}
    12×12 LinearMaps.WrappedMap{Float64} of
      12×12 Matrix{Float64}
  916428×916428 LinearMaps.WrappedMap{Float64} of
    916428×916428 Diagonal{Float64, Vector{Float64}}

In [5]:
outdegree[outdegree .== 0] .= n
R_inv = LinearMap(Diagonal((ones(n)./ outdegree)[:,1]))
# R_inv : 1/r_1 1/r_2 ... 1/r_n diagonal
# R_inv * A 하면 dangling row 처리가 안됨 (1/n 들어가야 할 자리에 0 이 들어가있음)

916428×916428 LinearMaps.WrappedMap{Float64} of
  916428×916428 Diagonal{Float64, Vector{Float64}}

In [11]:
# outdegree_inv = outdegree_inv + A_partial

In [13]:
p=0.8
A = LinearMap(convert.(Float64,md.A))
P = (1-p)/n * J + p * (R_inv * A + A_partial)

916428×916428 LinearMaps.LinearCombination{Float64} with 2 maps:
  916428×916428 LinearMaps.ScaledMap{Float64} with scale: 2.1823863958761623e-7 of
    916428×916428 LinearMaps.KroneckerMap{Float64} with 2 maps:
      76369×76369 LinearMaps.WrappedMap{Float64} of
        76369×76369 Matrix{Float64}
      12×12 LinearMaps.WrappedMap{Float64} of
        12×12 Matrix{Float64}
  916428×916428 LinearMaps.ScaledMap{Float64} with scale: 0.8 of
    916428×916428 LinearMaps.LinearCombination{Float64} with 2 maps:
      916428×916428 LinearMaps.CompositeMap{Float64} with 2 maps:
        916428×916428 LinearMaps.WrappedMap{Float64} of
          916428×916428 SparseMatrixCSC{Float64, Int64}
        916428×916428 LinearMaps.WrappedMap{Float64} of
          916428×916428 Diagonal{Float64, Vector{Float64}}
      916428×916428 LinearMaps.CompositeMap{Float64} with 2 maps:
        916428×916428 LinearMaps.KroneckerMap{Float64} with 2 maps:
          76369×76369 LinearMaps.WrappedMap{Float64} of
       

In [10]:
using IterativeSolvers
π1 = ones(n)./n
π1 = gmres(I-transpose(P), zeros(n))
# gmres!(π1,I-transpose(P), zeros(n))

916428-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 ⋮
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [125]:
count(iszero, π1)

916428

----------------------------------------------

In [1]:
using CSV
using DataFrames
data = CSV.read(download("https://web.stanford.edu/~hastie/ElemStatLearn/datasets/prostate.data"), DataFrame)

data[!,"age"] = convert.(Float64,data[:,"age"])
data[!,"pgg45"] = convert.(Float64,data[:,"pgg45"])
data[!,"svi"] = convert.(Float64,data[:,"svi"])
data[!,"gleason"] = convert.(Float64,data[:,"gleason"])


X = data[:, Not(["Column1","lpsa","train"])]
y = data[:, "lpsa"]


using Statistics
μ = mean.(eachcol(X))
σ = std.(eachcol(X))
n=size(X,1)

for i in 1:8
    X[:,i] = (X[:,i] .- μ[i])./σ[i]
end
X = [ones(n) X]


# split data
n = size(X, 1)
using StatsBase, DataFrames
n_train = convert(Int64, round(0.8*n))
idx = sample(1:n,n_train, replace=false)
Xtrain, ytrain = Matrix(X[idx, :]), y[idx, :]
Xtest, ytest = Matrix(X[Not(idx), :]), y[Not(idx), :]



using Random, LinearAlgebra, SparseArrays
using Convex
println("check")
t=1
s=Variable(1)
β̂dantzig = Variable(size(Xtrain,2))
println("check")
problem = minimize(s) # objective
problem.constraints += transpose(Xtrain)*(ytrain - Xtrain * β̂dantzig) <= s*ones(size(Xtrain,2))
problem.constraints += transpose(Xtrain)*(ytrain - Xtrain * β̂dantzig) >= -s*ones(size(Xtrain,2))
problem.constraints += sum(abs.(β̂dantzig)[2:end]) <= t
println("check")
# problem = minimize( norm( transpose(Xtrain) * (ytrain - Xtrain*β̂dantzig), Inf) )
# problem.constraints += norm(β̂dantzig[2:end],1)<= t

using SCS
opt = () -> SCS.Optimizer()
@time solve!(problem, opt)
println("check")

┌ Error: curl_easy_setopt: 48
└ @ Downloads.Curl /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Downloads/src/Curl/utils.jl:36
┌ Error: curl_easy_setopt: 48
└ @ Downloads.Curl /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Downloads/src/Curl/utils.jl:36
┌ Error: curl_easy_setopt: 48
└ @ Downloads.Curl /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Downloads/src/Curl/utils.jl:36


check
check
check
 14.327488 seconds (48.12 M allocations: 2.775 GiB, 3.79% gc time)
check
----------------------------------------------------------------------------
	SCS v2.1.4 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
----------------------------------------------------------------------------
Lin-sys: sparse-indirect, nnz in A = 222, CG tol ~ 1/iter^(2.00)
eps = 1.00e-05, alpha = 1.50, max_iters = 5000, normalize = 1, scale = 1.00
acceleration_lookback = 10, rho_x = 1.00e-03
Variables n = 19, constraints m = 36
Cones:	primal zero / dual free vars: 1
	linear vars: 35
Setup time: 4.73e-05s
----------------------------------------------------------------------------
 Iter | pri res | dua res | rel gap | pri obj | dua obj | kap/tau | time (s)
----------------------------------------------------------------------------
     0| 1.96e+19  8.37e+18  1.00e+00 -1.56e+21  1.55e+18  1.04e+21  2.61e-05 
   100| 1.70e-02  1.99e-02  1.91e-01  3.05e-01  4.73e-02 

┌ Warning: Problem status ALMOST_OPTIMAL; solution may be inaccurate.
└ @ Convex /Users/youp/.julia/packages/Convex/d5zVE/src/solution.jl:250


# 통계계산 과제3

In [1]:
using CSV
using DataFrames
data = CSV.read(download("https://web.stanford.edu/~hastie/ElemStatLearn/datasets/prostate.data"), DataFrame)
show(data, allcols=true)

┌ Error: curl_easy_setopt: 48
└ @ Downloads.Curl /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Downloads/src/Curl/utils.jl:36
┌ Error: curl_easy_setopt: 48
└ @ Downloads.Curl /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Downloads/src/Curl/utils.jl:36
┌ Error: curl_easy_setopt: 48
└ @ Downloads.Curl /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Downloads/src/Curl/utils.jl:36


97×11 DataFrame
 Row │ Column1  lcavol     lweight  age    lbph       svi    lcp        gleason  pgg45  lpsa       train 
     │ Int64    Float64    Float64  Int64  Float64    Int64  Float64    Int64    Int64  Float64    Bool  
─────┼───────────────────────────────────────────────────────────────────────────────────────────────────
   1 │       1  -0.579818  2.76946     50  -1.38629       0  -1.38629         6      0  -0.430783   true
   2 │       2  -0.994252  3.31963     58  -1.38629       0  -1.38629         6      0  -0.162519   true
   3 │       3  -0.510826  2.69124     74  -1.38629       0  -1.38629         7     20  -0.162519   true
   4 │       4  -1.20397   3.28279     58  -1.38629       0  -1.38629         6      0  -0.162519   true
   5 │       5   0.751416  3.43237     62  -1.38629       0  -1.38629         6      0   0.371564   true
   6 │       6  -1.04982   3.22883     50  -1.38629       0  -1.38629         6      0   0.765468   true
   7 │       7   0.737164  3.47352  

In [2]:
data[!,"age"] = convert.(Float64,data[:,"age"])
data[!,"pgg45"] = convert.(Float64,data[:,"pgg45"])
data[!,"svi"] = convert.(Float64,data[:,"svi"])
data[!,"gleason"] = convert.(Float64,data[:,"gleason"])


X = data[:, Not(["Column1","lpsa","train"])]
y = data[:, "lpsa"]

97-element Vector{Float64}:
 -0.4307829
 -0.1625189
 -0.1625189
 -0.1625189
  0.3715636
  0.7654678
  0.7654678
  0.8544153
  1.047319
  1.047319
  1.2669476
  1.2669476
  1.2669476
  ⋮
  3.6309855
  3.6800909
  3.7123518
  3.9843437
  3.993603
  4.029806
  4.1295508
  4.3851468
  4.6844434
  5.1431245
  5.477509
  5.5829322

In [3]:
using Statistics
μ = mean.(eachcol(X))
σ = std.(eachcol(X))
n=size(X,1)

for i in 1:8
    X[:,i] = (X[:,i] .- μ[i])./σ[i]
end
X = [ones(n) X]

97×9 DataFrame
 Row │ x1       lcavol     lweight     age         lbph       svi        lcp   ⋯
     │ Float64  Float64    Float64     Float64     Float64    Float64    Float ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │     1.0  -1.63736   -2.00621    -1.86243    -1.02471   -0.522941  -0.86 ⋯
   2 │     1.0  -1.98898   -0.722009   -0.787896   -1.02471   -0.522941  -0.86
   3 │     1.0  -1.57882   -2.18878     1.36116    -1.02471   -0.522941  -0.86
   4 │     1.0  -2.16692   -0.807994   -0.787896   -1.02471   -0.522941  -0.86
   5 │     1.0  -0.507874  -0.458834   -0.250631   -1.02471   -0.522941  -0.86 ⋯
   6 │     1.0  -2.03613   -0.933955   -1.86243    -1.02471   -0.522941  -0.86
   7 │     1.0  -0.519967  -0.362793    0.0180011   0.354858  -0.522941  -0.86
   8 │     1.0  -0.557313  -0.208757   -0.787896    0.990147  -0.522941  -0.86
   9 │     1.0  -1.80425   -0.208757   -2.26537    -1.02471   -0.522941  -0.86 ⋯
  10 │     1.0  -0.956085  -0.897266   -0.116315   -1.02471   -0.522941  -0.86
  11 │     1.0  -0.92936   -0.0578992   0.152317   -1.02471   -0.522941  -0.86
  ⋮  │    ⋮         ⋮          ⋮           ⋮           ⋮          ⋮          ⋮ ⋱
  88 │     1.0   0.323806  -0.606718   -0.250631   -1.02471    1.89255    0.34
  89 │     1.0   1.23668    2.54221     0.152317   -1.02471    1.89255    1.89 ⋯
  90 │     1.0   0.180156   0.154448    1.6298      0.57605    1.89255    0.70
  91 │     1.0   1.60906    1.10379     0.555266   -1.02471   -0.522941  -0.86
  92 │     1.0   1.00362    0.113497   -0.384948    0.860016   1.89255   -0.86
  93 │     1.0   1.25592    0.577607    0.555266   -1.02471    1.89255    1.07 ⋯
  94 │     1.0   2.09651    0.625489   -2.66832    -1.02471    1.89255    1.67
  95 │     1.0   1.3214    -0.543304   -1.59379    -1.02471    1.89255    1.89
  96 │     1.0   1.30029    0.338384    0.555266    1.00481    1.89255    1.24
  97 │     1.0   1.80037    0.807764    0.555266    0.232904   1.89255    2.20 ⋯
                                                   3 columns and 76 rows omitted

In [4]:
# split data
n = size(X, 1)
using StatsBase, DataFrames
n_train = convert(Int64, round(0.8*n))
idx = sample(1:n,n_train, replace=false)
Xtrain, ytrain = Matrix(X[idx, :]), y[idx, :]
Xtest, ytest = Matrix(X[Not(idx), :]), y[Not(idx), :]


([1.0 -1.6373556264810392 … -1.0421572891929798 -0.8644665073373063; 1.0 -1.98898046126935 … -1.0421572891929798 -0.8644665073373063; … ; 1.0 0.5720085322365001 … -1.0421572891929798 -0.8644665073373063; 1.0 1.2366820671589758 … 0.3426270539812537 1.2628887031079887], [-0.4307829; -0.1625189; … ; 3.6800909; 3.9843437])

In [6]:
using Random, LinearAlgebra, SparseArrays
using Convex
println("check")
t=1
s=Variable(1)
β̂dantzig = Variable(size(Xtrain,2))
println("check")
problem = minimize(s) # objective
problem.constraints += transpose(Xtrain)*(ytrain - Xtrain * β̂dantzig) <= s*ones(size(Xtrain,2))
problem.constraints += transpose(Xtrain)*(ytrain - Xtrain * β̂dantzig) >= -s*ones(size(Xtrain,2))
problem.constraints += sum(abs.(β̂dantzig)[2:end]) <= t
println("check")
# problem = minimize( norm( transpose(Xtrain) * (ytrain - Xtrain*β̂dantzig), Inf) )
# problem.constraints += norm(β̂dantzig[2:end],1)<= t

using SCS
opt = () -> SCS.Optimizer()
@time solve!(problem, opt)
println("check")

check
check
check
 14.160663 seconds (48.04 M allocations: 2.775 GiB, 3.98% gc time)
check
----------------------------------------------------------------------------
	SCS v2.1.4 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
----------------------------------------------------------------------------
Lin-sys: sparse-indirect, nnz in A = 222, CG tol ~ 1/iter^(2.00)
eps = 1.00e-05, alpha = 1.50, max_iters = 5000, normalize = 1, scale = 1.00
acceleration_lookback = 10, rho_x = 1.00e-03
Variables n = 19, constraints m = 36
Cones:	primal zero / dual free vars: 1
	linear vars: 35
Setup time: 4.43e-05s
----------------------------------------------------------------------------
 Iter | pri res | dua res | rel gap | pri obj | dua obj | kap/tau | time (s)
----------------------------------------------------------------------------
     0| 2.01e+19  8.63e+18  1.00e+00 -1.57e+21  1.53e+18  1.03e+21  2.27e-05 
   100| 4.64e-02  4.25e-01  8.59e-02  1.13e+00  1.44e+00 

# 통계계산 과제2

In [1]:
using LinearAlgebra
function cgs(X::Matrix{T}) where T<:AbstractFloat
    n, p = size(X)
    Q = Matrix{T}(undef, n, p)
    R = zeros(T, p, p)
    for j=1:p
        Q[:, j] .= X[:, j]   # v_k 만들 때 x_k 에서 계속 빼줘야하기 때문.
        for i=1:j-1
            R[i, j] = dot(Q[:, i], X[:, j])
            Q[:, j] .-= R[i, j] * Q[:, i]    # proj한 벡터들 계속 빼주는 것 생각
        end
        R[j, j] = norm(Q[:, j])
        Q[:, j] /= R[j, j]
    end
    Q, R
end
function mgs!(X::Matrix{T}) where T<:AbstractFloat
    n, p = size(X)
    R = zeros(T, p, p)
    for j=1:p
        for i=1:j-1
            R[i, j] = dot(X[:, i], X[:, j])
            X[:, j] -= R[i, j] * X[:, i]
        end
        R[j, j] = norm(X[:, j])
        X[:, j] /= R[j, j]
    end
    X, R
end

mgs! (generic function with 1 method)

In [11]:
e = eps(Float32)
A = [1f0 1f0 1f0; e 0 0; 0 e 0; 0 0 e]
# machine epsilong 발생

4×3 Matrix{Float32}:
 1.0         1.0         1.0
 1.19209f-7  0.0         0.0
 0.0         1.19209f-7  0.0
 0.0         0.0         1.19209f-7

# cgs

In [36]:
function cgs_test!(X::Matrix{T}) where T<:AbstractFloat
    n, p = size(X)
    Q = Matrix{T}(undef, n, p)
    R = zeros(T, p, p)
    for j=1:p
        println("########## j = ",j, " ##########")
        Q[:, j] .= X[:, j]   # v_k 만들 때 x_k 에서 계속 빼줘야하기 때문.
        for i=1:j-1
            R[i, j] = dot(Q[:, i], X[:, j])
            Q[:, j] .-= R[i, j] * Q[:, i]    # proj한 벡터들 계속 빼주는 것 생각
            println("(i = ",i,", j = ", j,")")
            println(R[i,j],"     ", Q[:,j])
            if i==j-1 println("                                 □  r",i,j," = ",R[i,j], "     q",j," = ",Q[:,j]) end
        end
        R[j, j] = norm(Q[:, j])
        Q[:, j] /= R[j, j]
        println("**** j= ", j, " ****")
        println("r",j ,j," = ",R[j,j],", q",j," = ", Q[:,j])
        println()
    end
    Q, R
end

cgs_test! (generic function with 1 method)

In [37]:
e = eps(Float32)
A = [1f0 1f0 1f0; e 0 0; 0 e 0; 0 0 e]
# machine epsilong 발생
cgs_test!(A)

########## j = 1 ##########
**** j= 1 ****
r11 = 1.0, q1 = Float32[1.0, 1.1920929f-7, 0.0, 0.0]

########## j = 2 ##########
(i = 1, j = 2)
1.0     Float32[0.0, -1.1920929f-7, 1.1920929f-7, 0.0]
                                 □  r12 = 1.0     q2 = Float32[0.0, -1.1920929f-7, 1.1920929f-7, 0.0]
**** j= 2 ****
r22 = 1.6858739e-7, q2 = Float32[0.0, -0.70710677, 0.70710677, 0.0]

########## j = 3 ##########
(i = 1, j = 3)
1.0     Float32[0.0, -1.1920929f-7, 0.0, 1.1920929f-7]
(i = 2, j = 3)
0.0     Float32[0.0, -1.1920929f-7, 0.0, 1.1920929f-7]
                                 □  r23 = 0.0     q3 = Float32[0.0, -1.1920929f-7, 0.0, 1.1920929f-7]
**** j= 3 ****
r33 = 1.6858739e-7, q3 = Float32[0.0, -0.70710677, 0.0, 0.70710677]



(Float32[1.0 0.0 0.0; 1.1920929f-7 -0.70710677 -0.70710677; 0.0 0.70710677 0.0; 0.0 0.0 0.70710677], Float32[1.0 1.0 1.0; 0.0 1.6858739f-7 0.0; 0.0 0.0 1.6858739f-7])

In [41]:
function mgs_test!(X::Matrix{T}) where T<:AbstractFloat
    n, p = size(X)
    R = zeros(T, p, p)
    for j=1:p
        println("########## j = ",j, " ##########")
        for i=1:j-1
            R[i, j] = dot(X[:, i], X[:, j])
            X[:, j] -= R[i, j] * X[:, i]
            println("(i = ",i,", j = ", j,")")
            println(R[i,j],"     ", X[:,j])
            if i==j-1 println("                                 □  r",i,j," = ",R[i,j], "     q",j," = ",X[:,j]) end
        end
        R[j, j] = norm(X[:, j])
        X[:, j] /= R[j, j]
        println("**** j= ", j, " ****")
        println("r",j ,j," = ",R[j,j],", q",j," = ", X[:,j])
        println()
    end
    X, R
end

mgs_test! (generic function with 1 method)

In [42]:
e = eps(Float32)
A = [1f0 1f0 1f0; e 0 0; 0 e 0; 0 0 e]
# machine epsilong 발생
mgs_test!(A)

########## j = 1 ##########
**** j= 1 ****
r11 = 1.0, q1 = Float32[1.0, 1.1920929f-7, 0.0, 0.0]

########## j = 2 ##########
(i = 1, j = 2)
1.0     Float32[0.0, -1.1920929f-7, 1.1920929f-7, 0.0]
                                 □  r12 = 1.0     q2 = Float32[0.0, -1.1920929f-7, 1.1920929f-7, 0.0]
**** j= 2 ****
r22 = 1.6858739e-7, q2 = Float32[0.0, -0.70710677, 0.70710677, 0.0]

########## j = 3 ##########
(i = 1, j = 3)
1.0     Float32[0.0, -1.1920929f-7, 0.0, 1.1920929f-7]
(i = 2, j = 3)
8.4293696e-8     Float32[0.0, -5.9604645f-8, -5.960464f-8, 1.1920929f-7]
                                 □  r23 = 8.4293696e-8     q3 = Float32[0.0, -5.9604645f-8, -5.960464f-8, 1.1920929f-7]
**** j= 3 ****
r33 = 1.4600097e-7, q3 = Float32[0.0, -0.40824828, -0.40824825, 0.81649655]



(Float32[1.0 0.0 0.0; 1.1920929f-7 -0.70710677 -0.40824828; 0.0 0.70710677 -0.40824825; 0.0 0.0 0.81649655], Float32[1.0 1.0 1.0; 0.0 1.6858739f-7 8.4293696f-8; 0.0 0.0 1.4600097f-7])

In [ ]:
########################################## r23, q3 에서 문제발생 #############################################

In [75]:


q2 = [0.0, -1.1920929f-7, 0.0, 1.1920929f-7]
x3_c = [1, 0, 0, 1.1920929f-7]
x3_m = [0.0, -1.1920929f-7, 0.0, 1.1920929f-7]
q2 = convert(Vector{Float32}, q2)
x3_c = convert(Vector{Float32}, x3_c)
x3_m = convert(Vector{Float32}, x3_m)

4-element Vector{Float32}:
  0.0
 -1.1920929f-7
  0.0
  1.1920929f-7

In [74]:
println(dot(q2, x3_c))
println(dot(q2, x3_m))

1.4210855e-14
2.842171e-14


In [83]:
qq = [1.0 1.1920929f-7 0.0 0.0 ; 0.0 -0.70710677 0.70710677 0.0]
qq = convert(Array{Float32}, qq)
qq=transpose(qq)

4×2 transpose(::Matrix{Float32}) with eltype Float32:
 1.0          0.0
 1.19209f-7  -0.707107
 0.0          0.707107
 0.0          0.0

In [84]:
transpose(qq)*qq

2×2 Matrix{Float32}:
  1.0         -8.42937f-8
 -8.42937f-8   1.0